fix: Liqi error dealing with aka dora
Apricot-S/majsoulrpa pull request #179
Opened 2024-02-24 19:55 UTC by smly

立直時のエラーを解消するためのPRです。

## エラー発生条件

赤ドラと対応する5の数牌が手牌にあり、かつこれらが立直時の打牌候補であるときに `InvalidOperation` 例外が発生します。
例外の発生場所は `MatchPresentation` の `_operate_liqi()` 内の `candidate_dapai_list` に対するバリデーション処理です。

具体例として、以下の状態で例外が発生します。

```
shoupai = ["2m", "7m", "8m", "9m", "3p", "4p", "5p", "4s", "0s", "5s", "6s", "9s", "9s"]
zimopai = 1m
op = LiqiOperation()
index = 9  # 5s
```

これは LiqiOperation インスタンスを作成するときに与えられるデータに赤ドラの `0s` のみが `data["combinations"]: list[str]` として受け取り、`5s` が含まれていないために発生します。

## 実装

_common.py に赤ドラを対応する5の数牌に変換する関数 `deaka()` を定義し、これに適用したあとで `candidate_dapai_list` に対するバリデーション処理を実行するよう修正しました。
あわせて `_operate_liqi()` に対するテストを追加しています。

2024-02-25 17:04 UTC, Apricot-S requested changes
- この問題は、立直宣言牌候補に赤と黒の5が両方あるとき、APIには赤の方しか含まれていないために発生するという認識でよいですか?

- `tests`ディレクトリ直下にも`__init__.py`が必要ではありませんか?

2024-02-26 02:52 UTC, smly commented on src/majsoulrpa/presentation/match/_common.py
> +def deaka(tile: str) -> str:
Mortal の同様の関数から関数名をもってきました https://github.com/Equim-chan/Mortal/blob/9861007986af2081e696ee7fab530e5598ac8d3f/libriichi/src/tile.rs#L68

2024-02-26 02:53 UTC, smly commented on src/majsoulrpa/presentation/match/match.py
> +        # When 5{p,m,s} and the corresponding red dora are in the hand.
m,p,s で統一されたほうが望ましいため修正します

2024-02-26 02:56 UTC, smly commented on tests/test_presentation/test_match.py
> +        def _dapai(self, index: int, dapai: list[str]) -> None:
特に理由はないです。可読性のため `forbidden_tiles` に名前をあわせる変更差分を追加します。

2024-02-26 03:10 UTC, smly commented
> この問題は、立直宣言牌候補に赤と黒の5が両方あるとき、APIには赤の方しか含まれていないために発生するという認識でよいですか?

はい、そうです。

> testsディレクトリ直下にも__init__.pyが必要ではありませんか?

tests ディレクトリ直下にテストコードがないため不要と判断しました。
基本的に `__init__.py` は不要です。test_presentation ディレクトリに `__init__.py` が配置されているのは、このディレクトリにテストコードがあり、ruff の implicit-namespace-package (INP001) を回避するためのものです。また将来的にテスト用の共通コード（複雑な Mock を作成する場合など）を配置する際、これを import させたいときに必要になるため配置しています。

以下のコードでテストを実行できることを確認しています。

```
❯ poetry run pytest --no-summary --no-header
================================== test session starts ===================================
collected 1 item                                                                         

tests/test_presentation/test_match.py .                                            [100%]

=================================== 1 passed in 0.98s ====================================
❯ file tests/test_presentation/__init__.py
tests/test_presentation/__init__.py: empty
❯ file tests/__init__.py
tests/__init__.py: cannot open `tests/__init__.py' (No such file or directory)
```

夜に用事があるため深夜あるいは明日以降に差分追加と返信をします。

2024-02-26 04:12 UTC, Apricot-S commented on src/majsoulrpa/presentation/match/_common.py
> +def deaka(tile: str) -> str:
承知しました。
下の`akaize`と合わせて考えると、decode、dequeueなどの"de"と同じ用法でしょうか

関数名のみとはいえ、AGPLのコードを参考にしてMITに実装してよいかちょっと引っかかってます。
この程度なら問題ないのか…

2024-02-26 13:21 UTC, Apricot-S commented on tests/test_presentation/test_match.py
テストケースについて、ツモ切り立直のテストの追加も必要ですね。
槓子と同じく、別のコミットで追加で大丈夫です。

2024-02-28 05:03 UTC, smly commented on pyproject.toml
> +testpaths = ["tests"]
不要と考えています。[pytest のドキュメント](https://docs.pytest.org/en/7.2.x/explanation/goodpractices.html#tests-outside-application-code) を見たところ3通りの実行方法がありそうです。

1. editable install する
2. 環境変数 PYTNONPATH で相対パスを指定する
3. pyproject.toml に相対パスを指定する

最近の poetry であれば `poetry install` を実行することで [editable mode でインストールする](https://python-poetry.org/docs/basic-usage/#operating-modes) ため、(2), (3) は不要になります。
一度 `poetry install` を実行すれば、あとはコードを修正して `poetry run pytest` を実行することで修正差分のテストができます。

2024-02-28 05:05 UTC, smly commented on src/majsoulrpa/presentation/match/match.py
> +        # When 5{p,m,s} and the corresponding red dora are in the hand.
[6d04d03](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/6d04d039d880340c637f984e7dfed5a582584100) にて修正

2024-02-28 05:05 UTC, smly commented on tests/test_presentation/test_match.py
> +        def _dapai(self, index: int, dapai: list[str]) -> None:
[931cbfa](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/931cbfa23a38c87e2dc9115a4a2cfab88a8a1bd7) にて修正

2024-02-28 05:13 UTC, smly commented on src/majsoulrpa/presentation/match/_common.py
> +def deaka(tile: str) -> str:
`normalize_akadora()` にリネームしました [a7bb24d](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/a7bb24d3bf24491931d0d892def5c91c05aa8cb0)

2024-02-28 06:46 UTC, smly commented on src/majsoulrpa/presentation/match/match.py
> +                _common.deaka(self.zimopai or "")
`or ""` は型エラー対応のために追加しました。ご指摘の通り `self.zimopai` が None の場合の validation ができていません。

[130d83f](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/130d83f235566781970399afa54e01b03a654539) にて対応しました。

* `self.zimopai` が None であるか否かの validation を立直ボタンクリック成功直後に移動
* if-elif-else 文のリファクタ。可読性向上のためエラーメッセージごとに if 文を分割して if のネストを解消しました。
* テストコードにて、`_zimopai` を書き換えていたコードを `zimopai` を書き換えるよう変更。これは `_round_state` が MagicMock オブジェクトであるために `_round_state.zimopai` を参照したとき `_zimopai` ではなく MagicMock が返却されていたため。結果として適切にテストされていなかった。

2024-02-28 09:23 UTC, Apricot-S requested changes

2024-02-28 09:27 UTC, smly commented on tests/test_presentation/test_match.py
槓子のテストを [10c40bc](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/10c40bc249f3d5a0130c2d42007c03f0d0cae1c1) にて追加。

ツモ切り立直のテストについては [130d83f](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/130d83f235566781970399afa54e01b03a654539) にて追加しています。

2024-02-28 09:59 UTC, Apricot-S requested changes

2024-02-28 09:59 UTC, Apricot-S commented on tests/test_presentation/test_match.py
細かいところで申し訳ないのですが、雀魂のAPIでは槓はKongではなくGangなので、`kong`になっている箇所(コメント含む)は`gang`に変更してください。

2024-02-28 10:02 UTC, smly commented
[4fa4e26](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/4fa4e26fe9db5a09cceb1485cf2554b67073fad2) にて `kong` を `gang` に置換しまいた。

2024-02-28 10:02 UTC, smly commented on tests/test_presentation/test_match.py
[4fa4e26](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/4fa4e26fe9db5a09cceb1485cf2554b67073fad2) にて kong を gang に置換しまいた。

2024-02-28 10:18 UTC, Apricot-S commented on tests/test_presentation/test_match.py
> +        ]
手牌の並びについて、5pと0pの並びは合っていますか?
_hand_inの正規表現を確認したところ、0pの方が先に来ると思います。
ゲーム画面でもそのようになっています。

何か意図があれば教えてください。

2024-02-28 10:22 UTC, smly commented on tests/test_presentation/test_match.py
> +        ]
誤りです。[a45997d](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/a45997d07db96a349d7795b6fe13296982965c8a) にて修正しました

2024-02-28 10:37 UTC, Apricot-S commented on tests/test_presentation/test_match.py
> +    assert op.candidate_dapai_list == ["0p"]
一応確認ですが、宣言牌候補に6pがないのはテスト内容が分かりにくくなるからという理解でよいですか?
今回の場合、6pを切ってもツモり四暗刻の形になります。

2024-02-28 10:45 UTC, smly commented on tests/test_presentation/test_match.py
> +    assert op.candidate_dapai_list == ["0p"]
気づいていなかったです。実装の確認として問題ないですが、想定されない状況でのテスト事例は望ましくないです。[2710b62](https://github.com/Apricot-S/majsoulrpa/pull/179/commits/2710b62d513f151c32fbe9f68be82335b6857e64) にて修正しました

2024-02-28 11:01 UTC, Apricot-S approved these changes

2024-02-28 11:01 UTC, merged